### PR TITLE
Upgrade to Jandex 2.3.0

### LINKED ISSUE #19: Update to Jandex 2.2.3.Final
Released since Mar 20, 2020. This plugin is still on 2.1.2.Final.

### PR DESCRIPTION
**Pull request by yrodiere**
Supersedes #24 (thanks @famod for the example :) )

Fixes #19.

Version bump to 1.1.0 relates to #21.

### CODE REVIEW

**Comment by yrodiere** [comment]
Hi @n1hility , could you please merge and release this?

It's necessary to fix https://github.com/quarkusio/quarkus/issues/17491, as the problem lies partly in how Jandex writes the index files.

**Comment by n1hility** [comment]
@yrodiere unfortunately I have been trying to sort out a release perms issue (can't publish). @stuartwdouglas should have access so when he is up later today I will get him to cut a release.

**Comment by famod** [comment]
I propose to include #23 and #27 into that release as well as those are no-brainers really.

**Comment by n1hility** [comment]
@famod ah yes good point merged.

**Comment by famod** [comment]
Thanks @n1hility!

**Pull request merged**
